import { db, listingsTable, inquiriesTable } from "@workspace/db";

const IMG = (name: string) => `/seed/${name}.png`;

const listings = [
  {
    title: "Villa contemporaine avec piscine à Anfa Supérieur",
    description:
      "Magnifique villa moderne de 4 chambres au cœur du quartier prisé d'Anfa Supérieur. Piscine extérieure chauffée, jardin paysager de 600m², salon double avec cheminée et grandes baies vitrées donnant sur la terrasse. Cuisine américaine entièrement équipée, suite parentale avec dressing. Garage 2 voitures, alarme, climatisation centralisée. Une adresse rare pour les amoureux du contemporain.",
    transaction: "sale",
    propertyType: "villa",
    price: 8500000,
    city: "Casablanca",
    neighborhood: "Anfa Supérieur",
    address: "Rue Abou Marouane Essadi, Anfa Supérieur",
    bedrooms: 4,
    bathrooms: 3,
    area: 380,
    images: [IMG("villa-casablanca"), IMG("kitchen-modern"), IMG("bedroom-elegant")],
    features: ["Piscine", "Jardin", "Garage", "Climatisation", "Alarme", "Cuisine équipée"],
    contactName: "Yassine El Mansouri",
    contactPhone: "+212 661 23 45 67",
    contactEmail: "yassine@dar-listings.ma",
    agencyName: "Anfa Prestige Immobilier",
    featured: true,
    latitude: 33.5731,
    longitude: -7.6298,
  },
  {
    title: "Appartement haut standing vue océan à L'Océan",
    description:
      "Splendide appartement traversant de 145m² au 7ème étage avec vue imprenable sur l'Atlantique. Trois chambres dont une suite parentale, double séjour lumineux ouvert sur une grande terrasse de 25m². Résidence sécurisée 24/7, ascenseur, parking sous-sol. Parquet massif, cuisine ouverte équipée, climatisation réversible. Idéal pour une famille ou investissement locatif premium.",
    transaction: "sale",
    propertyType: "apartment",
    price: 2950000,
    city: "Rabat",
    neighborhood: "L'Océan",
    address: "Avenue Hassan II, Résidence Atlantique",
    bedrooms: 3,
    bathrooms: 2,
    area: 145,
    images: [IMG("apartment-rabat"), IMG("kitchen-modern"), IMG("bedroom-elegant")],
    features: ["Vue mer", "Terrasse", "Ascenseur", "Parking", "Sécurité 24/7", "Climatisation"],
    contactName: "Khadija Benali",
    contactPhone: "+212 662 11 22 33",
    contactEmail: "khadija@dar-listings.ma",
    agencyName: "Capital Immo",
    featured: true,
    latitude: 34.0209,
    longitude: -6.8416,
  },
  {
    title: "Riad authentique entièrement rénové dans la Médina",
    description:
      "Joyau de la Médina de Marrakech : riad de caractère sur 3 niveaux avec patio central, fontaine en marbre et zellige fait main. Cinq chambres avec salles de bains privatives, salon traditionnel, salle à manger, cuisine professionnelle. Terrasse panoramique avec vue sur l'Atlas et la Koutoubia. Parfait pour maison d'hôtes ou résidence d'exception. Charme intact, prestations modernes.",
    transaction: "sale",
    propertyType: "riad",
    price: 5400000,
    city: "Marrakech",
    neighborhood: "Médina - Bab Doukkala",
    address: "Derb El Hammam, Médina",
    bedrooms: 5,
    bathrooms: 5,
    area: 290,
    images: [IMG("riad-marrakech"), IMG("bedroom-elegant"), IMG("kitchen-modern")],
    features: ["Patio", "Fontaine", "Terrasse panoramique", "Zellige", "Cheminée", "Hammam"],
    contactName: "Omar Idrissi",
    contactPhone: "+212 663 88 99 00",
    contactEmail: "omar@dar-listings.ma",
    agencyName: "Médina Heritage",
    featured: true,
    latitude: 31.6295,
    longitude: -7.9811,
  },
  {
    title: "Villa avec vue mer à Cap Spartel",
    description:
      "Élégante villa de 320m² perchée sur les hauteurs de Cap Spartel. Vue panoramique sur le détroit de Gibraltar. Quatre chambres, salon avec cheminée, salle à manger ouverte sur le jardin méditerranéen. Piscine à débordement, terrasse en bois exotique, dépendance pour personnel. Quartier résidentiel calme, à 15 minutes du centre de Tanger.",
    transaction: "sale",
    propertyType: "villa",
    price: 6200000,
    city: "Tanger",
    neighborhood: "Cap Spartel",
    address: "Route de Cap Spartel, Charf",
    bedrooms: 4,
    bathrooms: 3,
    area: 320,
    images: [IMG("villa-tangier"), IMG("kitchen-modern"), IMG("bedroom-elegant")],
    features: ["Vue mer", "Piscine", "Jardin", "Cheminée", "Dépendance", "Vue panoramique"],
    contactName: "Salma Bennani",
    contactPhone: "+212 664 55 66 77",
    contactEmail: "salma@dar-listings.ma",
    agencyName: "Détroit Immobilier",
    featured: true,
    latitude: 35.7806,
    longitude: -5.9239,
  },
  {
    title: "Maison de plage à Founty",
    description:
      "Charmante maison de bord de mer à 200m de la plage de Founty. Trois chambres, grand séjour ouvert sur terrasse couverte, cuisine moderne équipée. Jardin avec barbecue, garage. Idéal résidence secondaire ou location saisonnière. Quartier calme et familial, accès direct à la corniche.",
    transaction: "sale",
    propertyType: "house",
    price: 3100000,
    city: "Agadir",
    neighborhood: "Founty",
    address: "Avenue de la Plage, Founty",
    bedrooms: 3,
    bathrooms: 2,
    area: 210,
    images: [IMG("house-agadir"), IMG("apartment-rabat"), IMG("bedroom-elegant")],
    features: ["Proche plage", "Jardin", "Terrasse", "Garage", "Barbecue"],
    contactName: "Hassan Tazi",
    contactPhone: "+212 665 44 33 22",
    contactEmail: "hassan@dar-listings.ma",
    agencyName: "Souss Immo",
    featured: false,
    latitude: 30.4202,
    longitude: -9.5982,
  },
  {
    title: "Studio meublé moderne à louer - Gauthier",
    description:
      "Joli studio de 38m² entièrement meublé et équipé au cœur du quartier dynamique de Gauthier. Idéal jeune actif ou étudiant. Coin nuit séparé, kitchenette équipée, salle d'eau moderne. Résidence sécurisée avec ascenseur. Charges incluses. Disponible immédiatement.",
    transaction: "rent",
    propertyType: "studio",
    price: 5500,
    city: "Casablanca",
    neighborhood: "Gauthier",
    address: "Rue Jean Jaurès, Gauthier",
    bedrooms: 0,
    bathrooms: 1,
    area: 38,
    images: [IMG("studio-modern"), IMG("kitchen-modern")],
    features: ["Meublé", "Équipé", "Ascenseur", "Sécurité", "Climatisation"],
    contactName: "Nadia Alaoui",
    contactPhone: "+212 666 77 88 99",
    contactEmail: "nadia@dar-listings.ma",
    agencyName: "Gauthier Locations",
    featured: false,
    latitude: 33.5892,
    longitude: -7.6336,
  },
  {
    title: "Appartement F4 à louer - Hassan",
    description:
      "Spacieux appartement de 130m² dans le quartier prestigieux de Hassan, à proximité du parlement et des ambassades. Trois chambres, double salon, cuisine équipée, deux salles de bains. Balcon avec vue dégagée. Résidence calme avec gardien. Parking privatif inclus.",
    transaction: "rent",
    propertyType: "apartment",
    price: 12000,
    city: "Rabat",
    neighborhood: "Hassan",
    address: "Avenue Allal Ben Abdellah, Hassan",
    bedrooms: 3,
    bathrooms: 2,
    area: 130,
    images: [IMG("apartment-rabat"), IMG("kitchen-modern"), IMG("bedroom-elegant")],
    features: ["Balcon", "Parking", "Gardien", "Cuisine équipée", "Climatisation"],
    contactName: "Mehdi El Fassi",
    contactPhone: "+212 667 12 34 56",
    contactEmail: "mehdi@dar-listings.ma",
    agencyName: "Hassan Premium",
    featured: false,
    latitude: 34.0151,
    longitude: -6.8326,
  },
  {
    title: "Riad à louer pour événements - Médina Fès",
    description:
      "Riad d'exception au cœur de la médina de Fès, disponible à la location longue durée. Six chambres, deux patios, terrasse panoramique sur la ville. Mobilier traditionnel d'époque, hammam privé, salle à manger pour 20 personnes. Idéal pour activité d'hébergement touristique ou résidence familiale étendue.",
    transaction: "rent",
    propertyType: "riad",
    price: 28000,
    city: "Fès",
    neighborhood: "Médina - Fès El Bali",
    address: "Derb Bensouda, Médina",
    bedrooms: 6,
    bathrooms: 6,
    area: 340,
    images: [IMG("riad-marrakech"), IMG("bedroom-elegant"), IMG("kitchen-modern")],
    features: ["Hammam", "Deux patios", "Terrasse", "Mobilier d'époque", "Cheminée"],
    contactName: "Fatima Zahra Berrada",
    contactPhone: "+212 668 23 45 67",
    contactEmail: "fatima@dar-listings.ma",
    agencyName: "Fès Heritage",
    featured: false,
    latitude: 34.0639,
    longitude: -4.9761,
  },
  {
    title: "Terrain constructible 1200m² - Bouskoura Golf",
    description:
      "Beau terrain plat de 1200m² en bord de fairway dans le prestigieux Bouskoura Golf City. Titre foncier, viabilisé (eau, électricité, assainissement), permis de construire R+1. Quartier résidentiel haut de gamme à 20 minutes de Casablanca. Investissement sûr dans une zone en pleine valorisation.",
    transaction: "sale",
    propertyType: "land",
    price: 2400000,
    city: "Casablanca",
    neighborhood: "Bouskoura Golf City",
    address: "Bouskoura Golf City",
    bedrooms: 0,
    bathrooms: 0,
    area: 1200,
    images: [IMG("land-morocco")],
    features: ["Titre foncier", "Viabilisé", "Permis R+1", "Plat"],
    contactName: "Younes Chraibi",
    contactPhone: "+212 669 11 22 33",
    contactEmail: "younes@dar-listings.ma",
    agencyName: "Foncier Plus",
    featured: false,
    latitude: 33.4561,
    longitude: -7.6502,
  },
  {
    title: "Local commercial pied d'immeuble - Maârif",
    description:
      "Local commercial de 85m² avec vitrine sur grande artère commerçante du Maârif. Très forte fréquentation piétonne. Grande surface vitrée, arrière-boutique, sanitaires. Climatisation réversible. Convient à toute activité commerciale (boutique, restaurant, agence).",
    transaction: "rent",
    propertyType: "commercial",
    price: 22000,
    city: "Casablanca",
    neighborhood: "Maârif",
    address: "Boulevard Zerktouni, Maârif",
    bedrooms: 0,
    bathrooms: 1,
    area: 85,
    images: [IMG("office-commercial")],
    features: ["Vitrine", "Climatisation", "Forte fréquentation", "Pied d'immeuble"],
    contactName: "Rachid Belkadi",
    contactPhone: "+212 670 44 55 66",
    contactEmail: "rachid@dar-listings.ma",
    agencyName: "Maârif Business",
    featured: false,
    latitude: 33.5895,
    longitude: -7.6336,
  },
  {
    title: "Bureaux open space - Casa Finance City",
    description:
      "Plateau de bureaux de 220m² au cœur de Casa Finance City. Open space modulable, deux salles de réunion, kitchenette, terrasse. Tour de standing avec accès sécurisé, parking, restaurant inter-entreprises. Vue exceptionnelle sur la ville. Adresse stratégique pour entreprise en croissance.",
    transaction: "rent",
    propertyType: "office",
    price: 38000,
    city: "Casablanca",
    neighborhood: "Casa Finance City",
    address: "Tour CFC, Boulevard Sidi Mohammed Ben Abdellah",
    bedrooms: 0,
    bathrooms: 2,
    area: 220,
    images: [IMG("office-commercial"), IMG("kitchen-modern")],
    features: ["Open space", "Salles de réunion", "Vue panoramique", "Parking", "Sécurité"],
    contactName: "Imane Lahlou",
    contactPhone: "+212 671 88 99 00",
    contactEmail: "imane@dar-listings.ma",
    agencyName: "CFC Office",
    featured: true,
    latitude: 33.5407,
    longitude: -7.6537,
  },
  {
    title: "Maison traditionnelle rénovée - Mellah Marrakech",
    description:
      "Authentique maison marocaine de 180m² dans le quartier historique du Mellah. Trois niveaux, quatre chambres, deux salons traditionnels, terrasse avec vue sur l'Atlas. Rénovation soignée respectant le caractère d'origine : tadelakt, bejmat, plafonds peints. Coup de cœur garanti.",
    transaction: "sale",
    propertyType: "house",
    price: 1850000,
    city: "Marrakech",
    neighborhood: "Mellah",
    address: "Derb El Mellah, Médina",
    bedrooms: 4,
    bathrooms: 2,
    area: 180,
    images: [IMG("riad-marrakech"), IMG("bedroom-elegant"), IMG("apartment-rabat")],
    features: ["Tadelakt", "Bejmat", "Terrasse vue Atlas", "Rénové", "Cheminée"],
    contactName: "Aziz Bouazza",
    contactPhone: "+212 672 33 44 55",
    contactEmail: "aziz@dar-listings.ma",
    agencyName: "Médina Heritage",
    featured: false,
    latitude: 31.6238,
    longitude: -7.9869,
  },
  {
    title: "Appartement neuf vue mer - Marina d'Agadir",
    description:
      "Appartement neuf de 95m² livré clé en main dans une résidence haut standing de la Marina d'Agadir. Deux chambres, séjour lumineux ouvert sur grande terrasse de 18m² avec vue panoramique sur le port. Cuisine américaine équipée, climatisation, double vitrage. Piscine commune, salle de sport, conciergerie 24/7.",
    transaction: "sale",
    propertyType: "apartment",
    price: 1750000,
    city: "Agadir",
    neighborhood: "Marina",
    address: "Marina d'Agadir, Front de mer",
    bedrooms: 2,
    bathrooms: 2,
    area: 95,
    images: [IMG("apartment-rabat"), IMG("house-agadir"), IMG("kitchen-modern")],
    features: ["Vue mer", "Terrasse", "Piscine commune", "Salle de sport", "Conciergerie", "Neuf"],
    contactName: "Soukaina El Idrissi",
    contactPhone: "+212 673 22 11 00",
    contactEmail: "soukaina@dar-listings.ma",
    agencyName: "Marina Properties",
    featured: true,
    latitude: 30.4244,
    longitude: -9.6331,
  },
  {
    title: "Villa familiale piscine à Souissi",
    description:
      "Belle villa familiale de 280m² sur un terrain de 500m² au cœur du quartier Souissi à Rabat. Cinq chambres dont une suite parentale, grand salon double, salle à manger, cuisine équipée. Piscine, jardin arboré, garage 2 voitures. Quartier ambassades, sécurisé et calme. Idéal famille.",
    transaction: "sale",
    propertyType: "villa",
    price: 5800000,
    city: "Rabat",
    neighborhood: "Souissi",
    address: "Avenue Mehdi Ben Barka, Souissi",
    bedrooms: 5,
    bathrooms: 4,
    area: 280,
    images: [IMG("villa-casablanca"), IMG("bedroom-elegant"), IMG("kitchen-modern")],
    features: ["Piscine", "Jardin", "Garage", "Sécurité", "Cuisine équipée"],
    contactName: "Rachida Squalli",
    contactPhone: "+212 674 11 22 33",
    contactEmail: "rachida@dar-listings.ma",
    agencyName: "Souissi Premium",
    featured: false,
    latitude: 33.9576,
    longitude: -6.8517,
  },
  {
    title: "Riad à louer - Quartier Habous Casablanca",
    description:
      "Charmant riad de 160m² dans le quartier des Habous, à louer non meublé. Patio central, trois chambres, salon traditionnel, terrasse. Architecture mauresque préservée. Stationnement à proximité. Bail longue durée.",
    transaction: "rent",
    propertyType: "riad",
    price: 14500,
    city: "Casablanca",
    neighborhood: "Habous",
    address: "Quartier Habous, Casablanca",
    bedrooms: 3,
    bathrooms: 2,
    area: 160,
    images: [IMG("riad-marrakech"), IMG("bedroom-elegant")],
    features: ["Patio", "Terrasse", "Architecture mauresque"],
    contactName: "Karim Jelloul",
    contactPhone: "+212 675 88 77 66",
    contactEmail: "karim@dar-listings.ma",
    agencyName: "Habous Locations",
    featured: false,
    latitude: 33.5731,
    longitude: -7.6151,
  },
  {
    title: "Appartement cosy à louer - Gueliz Marrakech",
    description:
      "Appartement de 75m² au 3ème étage avec ascenseur dans le quartier moderne du Gueliz. Deux chambres, séjour avec balcon, cuisine équipée, salle de bains. Proche de toutes commodités, restaurants, écoles. Disponible immédiatement.",
    transaction: "rent",
    propertyType: "apartment",
    price: 7800,
    city: "Marrakech",
    neighborhood: "Gueliz",
    address: "Avenue Mohammed V, Gueliz",
    bedrooms: 2,
    bathrooms: 1,
    area: 75,
    images: [IMG("apartment-rabat"), IMG("kitchen-modern")],
    features: ["Balcon", "Ascenseur", "Cuisine équipée", "Climatisation"],
    contactName: "Lamia Tahiri",
    contactPhone: "+212 676 44 55 66",
    contactEmail: "lamia@dar-listings.ma",
    agencyName: "Gueliz Living",
    featured: false,
    latitude: 31.6346,
    longitude: -8.0089,
  },
  {
    title: "Terrain agricole 5 hectares - Région Fès",
    description:
      "Beau terrain agricole de 5 hectares (50 000m²) à 25km de Fès. Sol fertile, accès route, point d'eau. Idéal pour exploitation oléicole, maraîchère ou projet agritouristique. Titre foncier, démarches simplifiées.",
    transaction: "sale",
    propertyType: "land",
    price: 1200000,
    city: "Fès",
    neighborhood: "Périphérie Fès",
    address: "Route de Sefrou",
    bedrooms: 0,
    bathrooms: 0,
    area: 50000,
    images: [IMG("land-morocco")],
    features: ["Agricole", "Titre foncier", "Point d'eau", "Accès route"],
    contactName: "Said Kabbaj",
    contactPhone: "+212 677 11 99 88",
    contactEmail: "said@dar-listings.ma",
    agencyName: "Terra Maroc",
    featured: false,
    latitude: 34.0331,
    longitude: -5.0003,
  },
  {
    title: "Penthouse exceptionnel vue baie - Tanger",
    description:
      "Penthouse de prestige de 200m² au sommet d'une tour résidentielle face à la baie de Tanger. Vue à 270° sur le détroit, l'Espagne, et les montagnes. Trois suites, double salon, cuisine américaine, terrasse panoramique de 80m² avec jacuzzi. Conciergerie, valet, parking double. Une adresse iconique.",
    transaction: "sale",
    propertyType: "apartment",
    price: 7900000,
    city: "Tanger",
    neighborhood: "Malabata",
    address: "Tour Atlantis, Boulevard Mohammed VI",
    bedrooms: 3,
    bathrooms: 4,
    area: 200,
    images: [IMG("villa-tangier"), IMG("apartment-rabat"), IMG("bedroom-elegant")],
    features: ["Vue panoramique", "Jacuzzi", "Conciergerie", "Valet", "Terrasse 80m²"],
    contactName: "Ahmed Ouazzani",
    contactPhone: "+212 678 33 22 11",
    contactEmail: "ahmed@dar-listings.ma",
    agencyName: "Détroit Prestige",
    featured: true,
    latitude: 35.7741,
    longitude: -5.7634,
  },
];

async function main() {
  console.log("Clearing existing data...");
  await db.delete(inquiriesTable);
  await db.delete(listingsTable);

  console.log(`Inserting ${listings.length} listings...`);
  await db.insert(listingsTable).values(listings);

  console.log("Done.");
  process.exit(0);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
